# Site Config
baseURL: "https://lynx.mrhaydendp.com"
languageCode: "en-us"
title: "Hayden Plumley | Lynx"
theme: "Lynx"

enableRobotsTXT: true
outputs:
    home: ["HTML"]

# Theme Config
params:
    env: production
    title: "Hayden Plumley | Lynx"
    author: Hayden Plumley
    description: "My social links, powered by Hugo & Lynx"
    keywords: ["Lynx", "Linktree", "About"]
    author:
        image: avatar.webp
        name: Hayden Plumley
        headline: "Stingray Survivor | Don't brake for bees | Software Developer | Linux User | Android Enthusiast"
        links:
            - github: "https://github.com/mrhaydendp"
            - x: "https://x.com/mrhaydendp"
            - email: "mailto:mrhaydendp@gmail.com"
            - link: "https://blog.mrhaydendp.com"

enableEmoji: true
disableKinds:
    - taxonomy
    - term

markup:
    highlight:
        noClasses: false
    goldmark:
        renderer:
            unsafe: true
