baseURL: "https://lynx.mrhaydendp.com"
locale: en-us
title: "Hayden Plumley | Lynx"
theme: Lynx

enableRobotsTXT: true
enableEmoji: true
disableKinds:
  - taxonomy
  - term

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Hayden Plumley | Lynx"
  description: "My social links, powered by Hugo and Lynx"
  keywords: ["Lynx", "Linktree", "About"]
  author:
    name: "Hayden Plumley"
    headline: "Tech enthusiast that enjoys tinkering with electronics, watching horror movies, and perfecting the art of brewing coffee."
    image: "avatar.webp" # path relative to static directory
    links:
      - github: "https://github.com/mrhaydendp"
      - x:
         href: "https://x.com/mrhaydendp"
         text: " "
      - email: "mailto:mrhaydendp@gmail.com"
      - link:
          href: "https://blog.mrhaydendp.com"
          text: "Blog"

module:
  hugoVersion:
    extended: false
    min: "0.158.0"

outputs:
  home:
    - html
